xxxxxxxxxxxxxxxx
x--x----------xx
x---x-----x----x
x--x-----------x
x--x---x-3---x-x
x--x------x----x
x-xx------x----x
x--------------x
x-x-------xxx--x
x---x--x---x--2x
x---x-xx----x-xx
xxxx---4----x-xx
x--x------x---xx
x--x-----------x
x----------1--xx
x-------xg-----x
x----------x--xx
xxxxxxxxxxxxxxxx
