xxxxxxxxxxxxxx
x-x---x------x
x---------x--x
x------x-----x
x--x-x--xx-xxx
xx-----------x
xg----x--x---x
x---------x--x
x--x---x-----x
x-x-----x--x-x
x-----x-----xx
x------------x
x-x-x--------x
x---x-----xx-x
x---3-----x--x
x-x-----x-x--x
x--x--------2x
x-----x-x--xxx
x-x-x-1------x
xxxxxxxxxxxxxx
