xxxxxxxxxxxxxxxx
x---xx---------x
x---xx---------x
x-----x----x---x
xxx---4---1----x
x-----x--------x
xx-x-----x3----x
x----xx--------x
xx2------------x
x-----xx---x---x
x-----x--------x
x--x-x---------x
xx-------x-----x
x------x-------x
x--x-----x----xx
x-xx----x------x
x-----g------x-x
xxxxxxxxxxxxxxxx
