xxxxxxxxxxxxxxx
x-----1-------x
x------x------x
x---------xx--x
x------x-x----x
xx------------x
xx-------2----x
x-3------x----x
xx--xx------x-x
x-------------x
x-x--------x--x
x----x--------x
x----x--------x
x---x------x--x
x---------x---x
x---x-x------xx
x--g---x--x--xx
xxxxxxxxxxxxxxx
