xxxxxxxxxxxxxxxxx
x-x------x------x
x-------x-x--3-xx
x---------------x
x--x-------xx---x
x---------------x
x------1---x----x
x--x---x--------x
x-----x--------xx
x--x-------x--g-x
x-x---2x-----4--x
x------------xx-x
xxxxxxxxxxxxxxxxx
