xxxxxxxxxxxxxxxxxxx
x-g-----------xx--x
x----x----xx------x
x---x-x---x---x---x
x---------x-x-----x
x-----x------x----x
xx-x--2---------x-x
x--------x-x---xx-x
x---------------x-x
x-----x--xx-------x
x-----1-------x-x-x
x-------x--------xx
x-x-3-----x-------x
x--x----------4-xxx
x-x------x---x---xx
x-xx----x---x-----x
xxxxxxxxxxxxxxxxxxx
