xxxxxxxxxxxxxxx
x-x---x-x----1x
x--x----x-----x
x-x-x---------x
x------------xx
xx--2---------x
x-------------x
x--------x----x
x---x-x--34---x
x---xg--------x
x--------x---xx
x---x----x---xx
x-xxx---------x
x--x--------xxx
x-----x--x----x
xxxxxxxxxxxxxxx
