xxxxxxxxxxxxxxxx
x-------------gx
x---------x----x
xx-x-----------x
x-x-------x-x--x
x-----x-x------x
x------x---xx-xx
xxx------------x
x--xx-x--x-----x
xx-----------xxx
x-x---x---x----x
x--------------x
x------x--2---xx
xx-----------1-x
xxxxxxxxxxxxxxxx
