xxxxxxxxxxxxxxxx
x--------------x
x---x----x-----x
x----x--g------x
x---2-----x-x--x
x---x-x--x----xx
x1-------x-----x
x-x--x--x-x--x-x
x-----x----xx--x
x-x------x--x--x
xx-----xx----x-x
xxxxxxxxxxxxxxxx
