xxxxxxxxxxxxxxxxx
x---4------x-x--x
x-1---x---------x
xx----x-g----x--x
xx-----------x--x
x-x------x------x
x------------x--x
x-----xxx-------x
x--3------x2---xx
x----x------x---x
xx---x----------x
x-----x---------x
x-------------x-x
xxxxxxxxxxxxxxxxx
