xxxxxxxxxxxxxx
x--------xx--x
x---xx2----x-x
x---------x--x
x---------x--x
x---x--x---x-x
x-x-----x--x-x
x----g------3x
x---1--x-----x
x---------x--x
x------------x
x------------x
x------------x
x-x-x---xx--xx
x----x-------x
x--------xx-xx
xxxxxxxxxxxxxx
