xxxxxxxxxxxxxxxx
x------------xxx
x------x-------x
x-xx--x--------x
x--2-x------x--x
xxx1-------x---x
x--x--x----x---x
x-----x------x-x
xx-xx--x-------x
x-x-x--------x-x
x-------x-xxx-xx
x-x-----------gx
x---x----x-----x
x---------x----x
xxxxxxxxxxxxxxxx
