xxxxxxxxxxxxxx
x-----xx----xx
xx---x----x-xx
x-x---------xx
x-x---x------x
x-----xgxx---x
x-x----------x
x-x-----3---xx
x-x-x-x--x---x
x---xx--x----x
x-------x----x
xx-x--x------x
xx-x-x-------x
x-------x--x-x
xx-x-x---x---x
x--1---x-----x
x---2----x---x
x-x------x---x
xxxxxxxxxxxxxx
