xxxxxxxxxxxxxxxxxx
x-x---x-x-xx-----x
x----------------x
x-------------xx-x
x-x--------2x-x--x
x----x-----x--x--x
x------x------x--x
x--3------x------x
x-----x----------x
x----------------x
xxx-----x-x--x---x
x-------xx-------x
x-------x-----xg-x
x-x--x-x---------x
x----x--------1--x
xxxxxxxxxxxxxxxxxx
