xxxxxxxxxxxxxxx
xxx----------xx
x--x-----x----x
x-----------x-x
x------x----g-x
xxx--x---x--x-x
x-------------x
xx---x--------x
x-----x-1-----x
x------x-----xx
x-xx--x-------x
x-x---x--x--x-x
x---x---x-----x
x-x-----------x
x------x-----xx
x----x--------x
xxxxxxxxxxxxxxx
