xxxxxxxxxxxxxxxx
x---x--------x-x
x-x------------x
xx-----1-------x
x-x-x----x-x---x
x---x--------x-x
x--x-----------x
x-------x-x----x
x-----xx-------x
x----g---------x
x--------------x
xxx----------x-x
x----------x--xx
x-x---------x--x
x------x-------x
xxxxxxxxxxxxxxxx
