xxxxxxxxxxxxxxxxxxx
x--x--------------x
x-------------x-x-x
x------xx----x-x--x
x--------x-----x--x
x---1x---x-x----x-x
x--x--------x-xx--x
xx----x----x------x
x----g---------x--x
xxxxxxxxxxxxxxxxxxx
