xxxxxxxxxxxxxxx
xx---xx--x----x
x-------------x
x-------x-----x
x---xx--------x
x-x--xx-------x
x--1----------x
x-----x-x-x---x
xg--x-xx------x
x-x--x---xx---x
x--x--xx-x----x
x-------------x
xxxxxxxxxxxxxxx
