xxxxxxxxxxxxxxxx
x--x---xx-----gx
x----x-----x---x
x---x---x------x
x----x--------xx
xx-------------x
x--xx-------xx-x
x1--x-------x-xx
xxx-x-x--------x
x-xx---x-------x
x------x-------x
xx-x-----------x
xxx------------x
x---------xx---x
x-x--x---------x
x------x--x----x
x----x-----xx--x
x----x---------x
xx------x------x
xxxxxxxxxxxxxxxx
