xxxxxxxxxxxxxxxxxxx
x--x--------------x
x-x---------------x
x-x---------x-----x
x-----x------x----x
x-------------x---x
x------x-------x--x
x---------x-------x
x-x---x------xxx--x
x-------x---xxx---x
x------g---x-x----x
x-------x-x-------x
x------------x----x
x-----xx----------x
x-------xx-x----x-x
x1---xx-----------x
xxxxxxxxxxxxxxxxxxx
