xxxxxxxxxxxxxxxxxxxx
x--x---------------x
x--------xx--------x
x----xxx-----x---x-x
x------x------x--x-x
x----x--x-xx----x--x
x----------------x-x
x-----x--1xx----g--x
xx----------x------x
x-x-------x-x------x
x-----------xx-x--xx
x----x--------x----x
x-------------x----x
x------------------x
x-----x-x----------x
x------------------x
xxxxxxxxxxxxxxxxxxxx
