xxxxxxxxxxxxxxxxxxx
x--x-----x------x-x
x-----x--x-----x--x
xxg---xx----------x
xx------x----xx---x
x------x-------x--x
x----x-x----xx---xx
x----x---------x-xx
x--xx---x-----x---x
x---------x--1-x--x
x---x----x--------x
x------x-xxx------x
x------xx-----x---x
x---------x-x---xxx
x-x--------x-----xx
x----x---------x--x
x--------------x--x
xxxxxxxxxxxxxxxxxxx
