xxxxxxxxxxxxxxxxxx
x-x-x--------x---x
x---x--x------x--x
x----------------x
x-------xxx------x
x-xx--------x----x
x-x--------------x
x--x----x------x-x
x----------------x
x-x----x--xxx----x
xx-x------------1x
x----------------x
x------------xx--x
x---x------------x
x-----x----------x
x---------x--x-xxx
xg----x-----x--xxx
xxxxxxxxxxxxxxxxxx
