xxxxxxxxxxxxxxx
xx--x---------x
x-x-x--x----x-x
x-----x---x-g-x
xx-------x----x
x----x1---x---x
x---------x--xx
x------xx-----x
x--x----------x
x-xx------xx--x
x-x-x---------x
x-------------x
x-------x-----x
x--------x----x
x-xxx----x----x
x---------x---x
x-----x---x---x
x--x--x-------x
xxxxxxxxxxxxxxx
