xxxxxxxxxxxxxxxxxxxx
xx--------------x--x
x---x----x-------x-x
x1-----------x-x---x
x-----------------xx
xx-xx-x--x---------x
x---xx---------x-g-x
x------xx----------x
xx-----x-----------x
xx-----x-----------x
x--x--x-x----x-x---x
x----------x----x--x
x------------------x
x----------------xxx
xxxxxxxxxxxxxxxxxxxx
