xxxxxxxxxxxxxxx
x------------xx
xx------------x
x---x--------xx
x-x---x-------x
x---------x---x
xx---x--1----xx
x---g---x---x-x
x----x--------x
x-x-----------x
x---------xxx-x
x-x-x---xx----x
x-x--xx------xx
x---------x---x
x-------x-----x
xxxxxxxxxxxxxxx
